### ISSUE TITLE
404 link to transparenzklagen.de

### ISSUE THREAD

**Issue by rugk** [okfde/fragdenstaat_de#177]
At the page where you can submit your Klagevorschlag (`https://fragdenstaat.de/klagen/anfrage/{ID}`) you do link to the privacy policy of transparenzklagen.de (i.e. https://www.transparenzklagen.de/datenschutzerklaerung/) at the end and let the user confirm one read this.

Well… as transparenzklagen.de seems to be down and now redirects to https://freiheitsrechte.org/, you only get a 404 error there.

BTW what happened to transparenzklagen.de, in general? Nothing is said anywhere…

**Comment by stefanw** [comment]
Fixed.

**Comment by rugk** [comment]
Still see the broken link in production, but maybe it's not deployed yet…

**Comment by stefanw** [comment]
Translations were bad, thanks for checking. Fixed now.

**Comment by rugk** [comment]
Can confirm it works now. :+1:
